export function geojsonToGpx(
  coordinates: [number, number][],
  name: string,
  distanceKm: number
): string {
  const trackpoints = coordinates
    .map(([lng, lat]) => `    <trkpt lat="${lat}" lon="${lng}"></trkpt>`)
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1"
  creator="Runner Circuit"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1
    http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>${name}</name>
    <desc>${distanceKm}km running route generated by Runner Circuit</desc>
  </metadata>
  <trk>
    <name>${name}</name>
    <trkseg>
${trackpoints}
    </trkseg>
  </trk>
</gpx>`;
}

export function downloadGpx(gpxString: string, filename: string) {
  const blob = new Blob([gpxString], { type: 'application/gpx+xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.gpx`;
  a.click();
  URL.revokeObjectURL(url);
}

export function googleMapsUrl(coordinates: [number, number][]): string {
  const origin = coordinates[0];
  const dest = coordinates[coordinates.length - 1];

  const step = Math.max(1, Math.floor(coordinates.length / 8));
  const waypoints = coordinates
    .filter((_, i) => i % step === 0)
    .slice(1, -1)
    .slice(0, 8)
    .map(([lng, lat]) => `${lat},${lng}`)
    .join('|');

  return (
    `https://www.google.com/maps/dir/?api=1` +
    `&origin=${origin[1]},${origin[0]}` +
    `&destination=${dest[1]},${dest[0]}` +
    `&waypoints=${waypoints}` +
    `&travelmode=walking`
  );
}
